# Generated by Django 4.1.7 on 2023-03-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptiontype',
            field=models.CharField(choices=[('N', 'NOT_SUBSCRIBED'), ('P', 'PREMIAM'), ('PP', 'PREMIMEPRO')], default='N', max_length=225),
        ),
    ]
