# Generated by Django 4.1.7 on 2023-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade_level',
            field=models.IntegerField(default=12),
        ),
    ]
