# Generated by Django 4.1.7 on 2023-03-17 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_choiceforquestion_videofinalquestions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='videofiles',
            name='other_matterials',
        ),
        migrations.RemoveField(
            model_name='videofiles',
            name='videofinalquestions',
        ),
        migrations.AddField(
            model_name='othermatterialsforthevideo',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.videofiles'),
        ),
        migrations.AddField(
            model_name='videofiles',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.course'),
        ),
        migrations.AddField(
            model_name='videofinalquestions',
            name='videos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Home.videofiles'),
        ),
    ]
