# Generated by Django 4.1.7 on 2023-03-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_donevideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='donequestions',
            name='student_answere',
            field=models.TextField(null=True),
        ),
    ]
